### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by biztex**

### CODE REVIEW

**Comment by bibi911110** [comment]
When can you show me the screen result?

**Comment by biztex** [comment]
well, it stopped for a while and then resumed again.
so, it will take some times.

**Comment by bibi911110** [comment]
i will contact with you here. okay?

**Comment by bibi911110** [comment]
Hi, there. When can I check your result?

**Comment by biztex** [comment]
Now, I have some issues.
I am implementing automatic logout function after some mins when user inactivity,
but it's doesn't work well,,,

**Comment by bibi911110** [comment]
When can I contact with you?

**Comment by biztex** [comment]
I am not sure.

**Pull request merged**
